add sf method for as.geojson
ropensci/geojson pull request #30
Opened 2018-08-21 21:31 UTC by cpsievert

2018-08-21 21:48 UTC, sckott commented
thanks @cpsievert - curious what the use case is that motivated this?

since it uses `sf`, i think we'd need to put `sf` in Suggests. This pkg itself doesn't depend yet on any of the pkgs with heavy system dependencies (rgeos, rgdal) so I'd prefer to put `sf` in Suggests.  

Does `sf::as_Spatial` cover all cases of objects with class `sf`?  are the other sf classes `sfg`, etc. covered by this method?

2018-08-21 22:26 UTC, cpsievert commented
> curious what the use case is that motivated this?

I'm designing an htmlwidget for a client where the front-end (i.e., JavaScript) consumes geojson. I'm using `as.geojson()` to make sure the user-provided R object is of the right type before translating to JSON. By supporting `sf` objects the user will have more flexibility as to what they feed into the function.

> Does sf::as_Spatial cover all cases of objects with class sf?

I believe so. The man page says it supports any of the following classes -- sf, sfc_POINT, sfc_MULTIPOINT, sfc_LINESTRING, sfc_MULTILINESTRING, sfc_POLYGON, or sfc_MULTIPOLYGON.

2018-08-21 23:19 UTC, sckott commented
okay, thanks for the background.

2018-08-21 23:21 UTC, sckott requested changes
Can you also:

- add `sf` to Suggests in DESCRIPTION file
- add an example to `as.geojson` inside a conditional block

2018-08-21 23:21 UTC, sckott commented on R/sp_to_geojson.R
> +  as.geojson(sf::as_Spatial(x))
at the top of this method, add a check for sf pkg

```r
if (!requireNamespace('sf')) stop('please install `sf`')
```

2018-08-22 17:37 UTC, sckott commented
thanks for the changes @cpsievert 

not sure if we can have the `setMethod` call for a package in Suggests, looking into that

2018-08-22 21:05 UTC, sckott approved these changes

2018-08-22 21:19 UTC, sckott commented
@cpsievert so with help from Jim Hester, I think we should change to removing https://github.com/ropensci/geojson/blob/5fd48ae1a67aec66eec5c97f3576e9e6d361b2a0/R/sp_to_geojson.R#L90-L94 completely from `R/sp_to_geojson.R`

and changing `R/onload.R` to have

```r
.onLoad <- function(libname, pkgname) {
  linting_opts()

  if (requireNamespace('sf', quietly = TRUE)) {
    setMethod("as.geojson", "sf", function(x) {
      as.geojson(sf::as_Spatial(x))
    })
  }
}
```

the only problem then is that the method is not in the docs for `as.geojson` - but users will know its there from the example you added and via `showMethods("as.geojson")`

2018-08-24 18:12 UTC, sckott commented
Thanks @cpsievert - looks good. Do you need this on CRAN to be able to use it, or is github version fine?

2018-08-24 18:12 UTC, merged

2018-08-24 18:29 UTC, cpsievert commented
No, github is fine, thanks!

2019-01-18 19:28 UTC, sckott commented
@cpsievert this is just accepted on CRAN now - binaries soon